### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by 2Keanan2** [gizmoguy/nz-covid-pass-verifier#4]
done all that i can to figure out how to use the python generators and verifier properly, but nothing. I change the variables in the code and click on it, opens quickly then closes without adding/changing the output files.
any instructions that make a bit more sense?

**Comment by gizmoguy** [comment]
Hi there,

This is a command line program so you'll need to run it from a command prompt to be able to set the correct arguments (rather than double clicking).

To run it from the command line we have some instructions you can read here on what the various options do:

https://github.com/nz-covid-pass/python-nz-covid-pass#readme

**Comment by 2Keanan2** [comment]
I'm using windows and that command prompt line doesn't work, on Linux you
can do "Sudo" but on windows it doesn't work

**Comment by gizmoguy** [comment]
Sorry, I can't supply windows instructions as I don't have a windows machine to test on.

You could try using the Windows Subsystem for Linux which might make the linux instructions work on Windows.
